name: kapua-continuous-integration
on: [push, pull_request] # Triggers the workflow on push or pull request events

env:
  BUILD_OPTS: ""
  CONFIG_OVERRIDES: "-Dcommons.db.schema=kapuadb -Dcommons.settings.hotswap=true -Dbroker.host=localhost"
  MAVEN_OPTS: "-Xmx4096m"

jobs:
  build-kapua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checks out a copy of the repository on the ubuntu-latest machine
      - uses: actions/setup-java@v1
        with:
          java-version: '8' # The JDK version to make available on the path.
          # java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          # architecture: x64 # (x64 or x86) - defaults to x64
      - uses: actions/cache@v2 # Cache local Maven repository to reuse dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -v
      # This action saves a list of existing images, the cache is created without them in the post run. It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - run: mvn -B ${BUILD_OPTS} -Pdocker -DskipTests clean install
      - run: bash <(curl -s https://codecov.io/bash)
  test-SavedImages:
    needs: build-kapua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - run: docker images
